# Generated by Django 5.1.2 on 2024-10-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
    ]
