# Generated by Django 5.1.2 on 2024-10-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_dish_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
    ]
