# Generated by Django 5.1.2 on 2024-10-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_remove_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, upload_to='recipes', verbose_name='Изображение'),
        ),
    ]
