# Generated by Django 5.1.2 on 2024-10-27 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_dish_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_of_week', models.CharField(choices=[('Monday', 'понедельник'), ('Tuesday', 'вторник'), ('Wednsday', 'среда'), ('Thursday', 'четверг'), ('Friday', 'пятница'), ('Saturday', 'суббота'), ('Sunday', 'воскресенье')], max_length=50, verbose_name='День недели')),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_menu', to='recipeapp.dish', verbose_name='Завтрак')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_menu', to='recipeapp.dish', verbose_name='Ужин')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_menu', to='recipeapp.dish', verbose_name='Обед')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
