# Generated by Django 5.1.2 on 2024-10-24 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_alter_dish_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='единицы измерения'),
        ),
    ]
