# Generated by Django 5.1.2 on 2024-10-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_remove_recipeitem_price_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
    ]
