# Generated by Django 5.1.2 on 2024-10-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0006_dish_description_alter_dish_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breakfast', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='recipeapp.dish', verbose_name='Завтрак')),
                ('dinner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='recipeapp.dish', verbose_name='Ужин')),
                ('lunch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='recipeapp.dish', verbose_name='Обед')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
